# -*- coding: utf-8 -*-
"""Final_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14GQle3CQVRWHbKZB2Qejo76KaIzn4Uef
"""

import json

# Загрузка данных из JSON файлов
with open('/content/alphabeths.json', 'r', encoding='utf-8') as file:
    alphabets = json.load(file)

with open('/content/most_word.json', 'r', encoding='utf-8') as file:
    frequent_words = json.load(file)

def detect_language(sentence):
    # Удаление знаков препинания и приведение к нижнему регистру
    sentence = ''.join(char for char in sentence if char.isalpha() or char.isspace()).lower()
    words = sentence.split()

    # Словарь для подсчета совпадений
    language_scores = {language: 0 for language in alphabets}

    # Подсчет совпадений алфавита

    for language, alphabet in alphabets.items():
        if set(sentence).issubset(alphabet):
            language_scores[language] += 1
    # Подсчет совпадений частотных слов
    for word in words:
        for language, freq_words in frequent_words.items():
            if word in freq_words:
                language_scores[language] += 1
    # Проверка
    if max(language_scores.values()) == 0:
        for char in set(sentence):
            for language, alphabet in alphabets.items():
                if char in alphabet:
                    language_scores[language] += 1
    # Определение языка с наибольшим количеством совпадений
    detected_language = max(language_scores, key=language_scores.get)
    return detected_language, language_scores

sentence = input("Enter the text to identify the language:")
language, scores = detect_language(sentence)
print(f"Detected language: {language}")